import pandas as pd
import numpy as np
from .base_factor import BaseFactor


class op_cost_margin(BaseFactor):
    """
    Operating Cost Profit Margin.
    This ratio calculates the profit margin generated by each unit of operating cost over the past 12 months (Trailing Twelve Months, TTM).
    Formula: Net Profit TTM / Operating Cost TTM.

    Operating Cost = Cost of Goods Sold + Selling Expenses + General & Administrative Expenses + Financial Expenses.
    """

    @property
    def name(self) -> str:
        return "op_cost_margin"

    @property
    def required_fields(self) -> list:
        return ['net_profit', 'oper_cost', 'sell_exp', 'admin_exp', 'fin_exp']

    def calculate(self, df: pd.DataFrame) -> pd.DataFrame:
        self.check_dependencies(df)

        # Calculate TTM Operating Costs (rolling sum of the last 4 quarters)
        operating_cost_ttm = (df['oper_cost'] + df['sell_exp'] + df['admin_exp'] + df['fin_exp']).rolling(4).sum()

        # Calculate TTM Net Profit (rolling sum of the last 4 quarters)
        net_profit_ttm = df['net_profit'].rolling(4).sum()

        # Operating Cost Profit Margin = Net Profit TTM / Operating Cost TTM
        factor_value = net_profit_ttm / operating_cost_ttm

        # Ensure numeric and handle division by zero
        factor_value = pd.to_numeric(factor_value, errors='coerce')

        result = pd.DataFrame({
            self.name: factor_value,
            'ts_code': df['ts_code'],
            'end_date': df['end_date']
        })

        if 'ann_date' in df.columns:
            result['ann_date'] = df['ann_date']

        return result

